---
- name: yadifa package installed
  apt:
    name: yadifa

- name: yadifad server configuration
  template:
    dest: /etc/yadifa/yadifad.conf
    src: templates/yadifad.conf.j2
  notify:
  - restart yadifa

- name: yadifa client configuration
  template:
    dest: /etc/yadifa.conf
    src: templates/yadifa.conf.j2
  when: yadifa_global_allow_control != "none"

- name: sync zone journals
  command: "yadifa -s {{ yadifa_cli_server }} sync {{ item.domain }} clean"
  loop: "{{ yadifa_zones }}"

- name: freeze zones prior to possible zone file updates
  command: "yadifa -s {{ yadifa_cli_server }} freeze {{ item.domain }}"
  loop: "{{ yadifa_zones }}"

- name: zone files
  copy:
    src: "{{ item.file }}"
    dest: "{{ yadifa_masters_dir }}/{{ item.file | basename }}"
  loop: "{{ yadifa_zones }}"
  notify:
  - reload zones

- name: unfreeze zones
  command: "yadifa -s {{ yadifa_cli_server }} unfreeze {{ item.domain }}"
  loop: "{{ yadifa_zones }}"

- name: yadifa service started
  service:
    name: yadifa
    state: started
    enabled: yes

- name: bind9utils package installed
  apt:
    name: bind9utils

- name: display DS records
  shell: "dig dnskey {{ item.domain }} @{{ yadifa_cli_server }} | dnssec-dsfromkey -f - {{ item.domain }}"
  loop: "{{ yadifa_zones }}"
