---
- name: yadifa package installed
  apt:
    name: yadifa

- name: yadifad server configuration
  template:
    dest: /etc/yadifa/yadifad.conf
    src: templates/yadifad.conf.j2
  notify:
  - restart yadifa

- name: yadifa client configuration
  template:
    dest: /etc/yadifa.conf
    src: templates/yadifa.conf.j2
  when: yadifa_global_allow_control != "none"

- name: zone files
  copy:
    src: "{{ item.file }}"
    dest: "{{ yadifa_masters_dir }}/{{ item.file | basename }}"
  loop: "{{ yadifa_zones }}"

- name: yadifa service started
  service:
    name: yadifa
    state: started
    enabled: yes
